version: "3.9"

services:
  web:
    image: book-review-backend
    env_file:
      - backend/book_api/.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: 'book-review'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '12345'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  frontend:
    image: book-review-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

volumes:
  postgres_data: