# Generated by Django 4.1.6 on 2023-02-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_remove_book_publication_date_author_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
