# Generated by Django 4.1.6 on 2023-02-18 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_store', '0006_alter_author_identifier_alter_book_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(null=True, upload_to='poster/')),
                ('books', models.ManyToManyField(related_name='book_clubs', to='book_store.book')),
                ('members', models.ManyToManyField(related_name='book_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Club',
                'verbose_name_plural': 'Book Clubs',
            },
        ),
    ]
