# Generated by Django 4.1.6 on 2023-02-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0008_alter_bookclub_options_bookclub_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclub',
            options={'ordering': ['created_at'], 'verbose_name': 'Book Club', 'verbose_name_plural': 'Book Clubs'},
        ),
    ]
