# Generated by Django 4.1.6 on 2023-02-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0010_alter_bookclub_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['identifier'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book Review', 'verbose_name_plural': 'Book Reviews'},
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='poster',
            field=models.ImageField(default='default.png', upload_to='poster/'),
        ),
    ]
