# Generated by Django 4.1.7 on 2024-04-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0013_userprofile_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
