# Generated by Django 4.1.7 on 2024-04-08 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0014_rename_profile_picture_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='books',
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.CreateModel(
            name='ClubBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CR', 'Currently Reading'), ('PR', 'Planning to Read'), ('AR', 'Already Read')], default='PR', max_length=2)),
                ('started_reading_at', models.DateTimeField(blank=True, null=True)),
                ('finished_reading_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='book_store.book')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_store.bookclub')),
            ],
            options={
                'unique_together': {('club', 'book')},
            },
        ),
    ]
