# Generated by Django 4.1.7 on 2024-04-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0015_remove_bookclub_books_alter_bookreview_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
